# Generated by Django 2.1 on 2019-04-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Hairstylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='hairstylist',
            name='type',
            field=models.ManyToManyField(to='hair.Type'),
        ),
        migrations.AddField(
            model_name='hairstyle',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hair.Type'),
        ),
    ]
