# Generated by Django 2.1 on 2019-04-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyle',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
