# Generated by Django 2.1 on 2019-04-17 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0002_hairstyle_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyle',
            name='image_url',
        ),
    ]
