# Generated by Django 2.1 on 2019-04-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0003_remove_hairstyle_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyle',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
